name: Philosopher Cow say
on:
  issue_comment:
    types: [created, deleted, edited]
jobs:
  setup:
    name: cowsay setup
    runs-on: ubuntu-latest
    steps:
    - name: update machina
      run: sudo apt update
    - name: install cowsay
      run: 
        sudo apt install -y cowsay
    - name: install fortune
      run: sudo apt install -y fortune
  cowsay:
    name: Enlight us with Cow knowledge
    runs-on: ubuntu-latest
    steps:
    - name: Say that to us
      run: fortune | cowsay
