name: Action Indeed
on:
  issue_comment:
    types: [created, deleted, edited]
jobs:
  cowsay:
    name: Things that a cow would say
    runs-on: ubuntu-latest
    steps:
    - name: update machina
      run: sudo apt update
    - name: install cowsay
      run: 
        sudo apt install -y cowsay
    - name: install fortune
      run: sudo apt install -y fortune
    - name: Philosopher Cow says
      run: |
        fortune | cowsay
